### ISSUE TITLE
The red hat

### ISSUE THREAD

**Issue by otakuapologist** [Happiness-plus/H-cooperative#1]
This non-clickable space is really confusing for users, I'm sure. Hover your mouse over any of the cards. 

The space that is actually clickable is quite narrow. Anyone casually hovering over these may categorize them as not clickable, because of this inconsistent behavior.

**Comment by Happiness-plus** [comment]
@otakuapologist you're going to have to show me what you mean?

**Comment by otakuapologist** [comment]
Here's the image. Seems I didn't post it.
![Uploading red hat coop.png…]()

**Comment by Happiness-plus** [comment]
@otakuapologist having full clickable cards could mess up things on mobile since the screen real estate is much smaller and you have to tap on things to move down.
