### ISSUE TITLE
About page.

### ISSUE THREAD

**Issue by otakuapologist** [Happiness-plus/H-cooperative#2]
The "learn more" button should link to this page (color for background attached). Page will say the following:

Why Choose Us?

1) Security of completion.
Our years of experience in development has solidified the best practices, which ensure that projects get done.

2) Backup creators instantly available.
We have backup contacts to take over work, should anyone be unable to work.

3) Creators paid after you approve the work.
We function as an escrow service. The funds to creators are paid out after you approve their work.

4) You own the commercial rights.
We sign a contract before we begin the work that lets you sell the games we make you.

5) We get you connected.
We know great publishers in the hentai games industry and will help you get connected with them. We'll advice you early on in product development to ensure compliance with commercial content restrictions.

6) We can promote you.
We've built a network of friendly websites to help create awareness of your product. Promotion is a paid addon service.

7) Free consultation.
You can ask us questions related to the western hentai games industry for no charge. Submit a question (this links to "get in touch")

At the bottom of the page, we could have the frontpage cards again.

**Comment by otakuapologist** [comment]
are we able to control that? if the texts are put into cards, should the be stacked on top of each otherrather? Can they be stacked?

**Comment by Happiness-plus** [comment]
Desktop
![Screenshot 2023-12-06 at 21-47-12 Hentai Cooperative LLC](https://github.com/Happiness-plus/H-cooperative/assets/48694096/9e76b1f2-946c-4677-b50c-2ab081a85f6a)

Phone
![Screenshot 2023-12-06 at 21-49-27 Hentai Cooperative LLC](https://github.com/Happiness-plus/H-cooperative/assets/48694096/14defcc8-d727-4c36-8a21-8a20b0cec349)

@otakuapologist remember smaller screens are harder to read on, I will have to make the text smaller to force two columns.

**Comment by Happiness-plus** [comment]
Done
